In [128]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [129]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
df_departments = pd.read_csv('../data/raw/departments.csv')
df_orders = pd.read_csv('../data/raw/orders.csv')
df_products = pd.read_csv('../data/raw/products.csv')
df_order_products__prior = pd.read_csv('../data/raw/order_products__prior.csv')
df_order_products__train = pd.read_csv('../data/raw/order_products__train.csv')

In [130]:
df_aisles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.2+ KB

In [131]:
df_departments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     object
dtypes: int64(1), object(1)
memory usage: 468.0+ bytes

In [132]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                object
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 182.7+ MB

In [133]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49688 entries, 0 to 49687
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49688 non-null  int64
 1   product_name   49688 non-null  object
 2   aisle_id       49688 non-null  int64
 3   department_id  49688 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [134]:
df_prod = df_products.merge(df_aisles, on="aisle_id", how="left") \
                    .merge(df_departments, on="department_id", how="left")

In [135]:
df_prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49688 entries, 0 to 49687
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49688 non-null  int64
 1   product_name   49688 non-null  object
 2   aisle_id       49688 non-null  int64
 3   department_id  49688 non-null  int64
 4   aisle          49688 non-null  object
 5   department     49688 non-null  object
dtypes: int64(3), object(3)
memory usage: 2.3+ MB

In [136]:
orders_prior_full = df_order_products__prior.merge(df_orders, on="order_id", how="left") \
                               .merge(df_prod, on="product_id", how="left")

orders_train_full = df_order_products__train.merge(df_orders, on="order_id", how="left") \
                               .merge(df_prod, on="product_id", how="left")

In [137]:
df = pd.concat([orders_prior_full, orders_train_full], axis=0, ignore_index=True)

In [138]:
df.to_csv("../data/processed/df_full.csv", index=False)

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33819106 entries, 0 to 33819105
Data columns (total 15 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   product_id              int64
 2   add_to_cart_order       int64
 3   reordered               int64
 4   user_id                 int64
 5   eval_set                object
 6   order_number            int64
 7   order_dow               int64
 8   order_hour_of_day       int64
 9   days_since_prior_order  float64
 10  product_name            object
 11  aisle_id                int64
 12  department_id           int64
 13  aisle                   object
 14  department              object
dtypes: float64(1), int64(10), object(4)
memory usage: 3.8+ GB

In [162]:
df_sample = pd.read_csv('../data/processed/df_full.csv', nrows=200000)

In [163]:
df_sample.shape

(200000, 15)

In [164]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                200000 non-null  int64
 1   product_id              200000 non-null  int64
 2   add_to_cart_order       200000 non-null  int64
 3   reordered               200000 non-null  int64
 4   user_id                 200000 non-null  int64
 5   eval_set                200000 non-null  object
 6   order_number            200000 non-null  int64
 7   order_dow               200000 non-null  int64
 8   order_hour_of_day       200000 non-null  int64
 9   days_since_prior_order  187329 non-null  float64
 10  product_name            200000 non-null  object
 11  aisle_id                200000 non-null  int64
 12  department_id           200000 non-null  int64
 13  aisle                   200000 non-null  object
 14  department              200000 non-null  object
dtypes: float64(1), int64(10), object(4)
memory usage: 22.9+ MB

In [165]:
df_sample.describe

<bound method NDFrame.describe of         order_id  product_id  add_to_cart_order  reordered  user_id eval_set  \
0              2       33120                  1          1   202279    prior
1              2       28985                  2          1   202279    prior
2              2        9327                  3          0   202279    prior
3              2       45918                  4          1   202279    prior
4              2       30035                  5          0   202279    prior
...          ...         ...                ...        ...      ...      ...
199995     21114       47766                  1          1    24406    prior
199996     21114       39097                  2          1    24406    prior
199997     21114       29270                  3          1    24406    prior
199998     21114       14835                  4          0    24406    prior
199999     21114       10638                  5          0    24406    prior

        order_number  order_dow  order_hour_of_day  days_since_prior_order  \
0                  3          5                  9                     8.0
1                  3          5                  9                     8.0
2                  3          5                  9                     8.0
3                  3          5                  9                     8.0
4                  3          5                  9                     8.0
...              ...        ...                ...                     ...
199995             7          1                 17                     8.0
199996             7          1                 17                     8.0
199997             7          1                 17                     8.0
199998             7          1                 17                     8.0
199999             7          1                 17                     8.0

                                             product_name  aisle_id  \
0                                      Organic Egg Whites        86
1                                   Michigan Organic Kale        83
2                                           Garlic Powder       104
3                                          Coconut Butter        19
4                                       Natural Sweetener        17
...                                                   ...       ...
199995                                    Organic Avocado        24
199996                   Gluten Free White Sandwich Bread       112
199997  Beet Apple Carrot Lemon Ginger Organic Cold Pr...        31
199998                               Safflower Mayonnaise        72
199999                         Patchouli Goat's Milk Soap        25

        department_id               aisle     department
0                  16                eggs     dairy eggs
1                   4    fresh vegetables        produce
2                  13   spices seasonings         pantry
3                  13       oils vinegars         pantry
4                  13  baking ingredients         pantry
...               ...                 ...            ...
199995              4        fresh fruits        produce
199996              3               bread         bakery
199997              7        refrigerated      beverages
199998             13          condiments         pantry
199999             11                soap  personal care

[200000 rows x 15 columns]>

In [166]:
df_sample.head(10)

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department
0,2,33120,1,1,202279,prior,3,5,9,8.0,Organic Egg Whites,86,16,eggs,dairy eggs
1,2,28985,2,1,202279,prior,3,5,9,8.0,Michigan Organic Kale,83,4,fresh vegetables,produce
2,2,9327,3,0,202279,prior,3,5,9,8.0,Garlic Powder,104,13,spices seasonings,pantry
3,2,45918,4,1,202279,prior,3,5,9,8.0,Coconut Butter,19,13,oils vinegars,pantry
4,2,30035,5,0,202279,prior,3,5,9,8.0,Natural Sweetener,17,13,baking ingredients,pantry
5,2,17794,6,1,202279,prior,3,5,9,8.0,Carrots,83,4,fresh vegetables,produce
6,2,40141,7,1,202279,prior,3,5,9,8.0,Original Unflavored Gelatine Mix,105,13,doughs gelatins bake mixes,pantry
7,2,1819,8,1,202279,prior,3,5,9,8.0,All Natural No Stir Creamy Almond Butter,88,13,spreads,pantry
8,2,43668,9,0,202279,prior,3,5,9,8.0,Classic Blend Cole Slaw,123,4,packaged vegetables fruits,produce
9,3,33754,1,1,205970,prior,16,5,17,12.0,Total 2% with Strawberry Lowfat Greek Strained...,120,16,yogurt,dairy eggs

In [167]:
df_sample.tail(10)

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department
199990,21113,4210,1,0,87932,prior,1,3,12,NaN,Whole Milk,84,16,milk,dairy eggs
199991,21113,3499,2,0,87932,prior,1,3,12,NaN,Peach Citrus Soda,77,7,soft drinks,beverages
199992,21113,42731,3,0,87932,prior,1,3,12,NaN,Original Citrus Sparkling Flavored Soda,77,7,soft drinks,beverages
199993,21113,8859,4,0,87932,prior,1,3,12,NaN,Natural Spring Water,115,7,water seltzer sparkling water,beverages
199994,21113,23909,5,0,87932,prior,1,3,12,NaN,2% Reduced Fat Milk,84,16,milk,dairy eggs
199995,21114,47766,1,1,24406,prior,7,1,17,8.0,Organic Avocado,24,4,fresh fruits,produce
199996,21114,39097,2,1,24406,prior,7,1,17,8.0,Gluten Free White Sandwich Bread,112,3,bread,bakery
199997,21114,29270,3,1,24406,prior,7,1,17,8.0,Beet Apple Carrot Lemon Ginger Organic Cold Pr...,31,7,refrigerated,beverages
199998,21114,14835,4,0,24406,prior,7,1,17,8.0,Safflower Mayonnaise,72,13,condiments,pantry
199999,21114,10638,5,0,24406,prior,7,1,17,8.0,Patchouli Goat's Milk Soap,25,11,soap,personal care

In [168]:
df_sample.describe()

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,aisle_id,department_id
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,187329.000000,200000.000000,200000.000000
mean,10554.357200,25544.779975,8.325475,0.590660,103282.343770,17.372745,2.735650,13.426435,10.931591,71.160405,9.967950
std,6080.122575,14090.622927,7.072321,0.491713,59482.632193,17.834455,2.083123,4.265644,8.613577,38.184946,6.289346
min,2.000000,1.000000,1.000000,0.000000,13.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,5281.000000,13524.000000,3.000000,0.000000,51508.000000,5.000000,1.000000,10.000000,5.000000,31.000000,4.000000
50%,10567.500000,25195.000000,6.000000,1.000000,102601.000000,11.000000,3.000000,13.000000,8.000000,83.000000,9.000000
75%,15807.000000,37766.000000,11.000000,1.000000,155588.000000,24.000000,5.000000,16.000000,14.000000,107.000000,16.000000
max,21114.000000,49688.000000,68.000000,1.000000,206208.000000,99.000000,6.000000,23.000000,30.000000,134.000000,21.000000

In [169]:
df_sample.isna().sum()

order_id                      0
product_id                    0
add_to_cart_order             0
reordered                     0
user_id                       0
eval_set                      0
order_number                  0
order_dow                     0
order_hour_of_day             0
days_since_prior_order    12671
product_name                  0
aisle_id                      0
department_id                 0
aisle                         0
department                    0
dtype: int64

In [170]:
df_sample = df_sample.drop(columns='days_since_prior_order')

In [171]:
df_sample.isna().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
user_id              0
eval_set             0
order_number         0
order_dow            0
order_hour_of_day    0
product_name         0
aisle_id             0
department_id        0
aisle                0
department           0
dtype: int64

In [172]:
df_aisles.head(10)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation
5         6                       other
6         7               packaged meat
7         8             bakery desserts
8         9                 pasta sauce
9        10            kitchen supplies

In [173]:
df_sample.head(10)

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,product_name,aisle_id,department_id,aisle,department
0,2,33120,1,1,202279,prior,3,5,9,Organic Egg Whites,86,16,eggs,dairy eggs
1,2,28985,2,1,202279,prior,3,5,9,Michigan Organic Kale,83,4,fresh vegetables,produce
2,2,9327,3,0,202279,prior,3,5,9,Garlic Powder,104,13,spices seasonings,pantry
3,2,45918,4,1,202279,prior,3,5,9,Coconut Butter,19,13,oils vinegars,pantry
4,2,30035,5,0,202279,prior,3,5,9,Natural Sweetener,17,13,baking ingredients,pantry
5,2,17794,6,1,202279,prior,3,5,9,Carrots,83,4,fresh vegetables,produce
6,2,40141,7,1,202279,prior,3,5,9,Original Unflavored Gelatine Mix,105,13,doughs gelatins bake mixes,pantry
7,2,1819,8,1,202279,prior,3,5,9,All Natural No Stir Creamy Almond Butter,88,13,spreads,pantry
8,2,43668,9,0,202279,prior,3,5,9,Classic Blend Cole Slaw,123,4,packaged vegetables fruits,produce
9,3,33754,1,1,205970,prior,16,5,17,Total 2% with Strawberry Lowfat Greek Strained...,120,16,yogurt,dairy eggs

In [174]:
df_sample = df_sample.drop(columns='aisle_id')

In [175]:
df_sample = df_sample.drop(columns='department_id')

In [176]:
df_sample = df_sample.drop(columns='eval_set')

In [177]:
df_sample.head(10)

,order_id,product_id,add_to_cart_order,reordered,user_id,order_number,order_dow,order_hour_of_day,product_name,aisle,department
0,2,33120,1,1,202279,3,5,9,Organic Egg Whites,eggs,dairy eggs
1,2,28985,2,1,202279,3,5,9,Michigan Organic Kale,fresh vegetables,produce
2,2,9327,3,0,202279,3,5,9,Garlic Powder,spices seasonings,pantry
3,2,45918,4,1,202279,3,5,9,Coconut Butter,oils vinegars,pantry
4,2,30035,5,0,202279,3,5,9,Natural Sweetener,baking ingredients,pantry
5,2,17794,6,1,202279,3,5,9,Carrots,fresh vegetables,produce
6,2,40141,7,1,202279,3,5,9,Original Unflavored Gelatine Mix,doughs gelatins bake mixes,pantry
7,2,1819,8,1,202279,3,5,9,All Natural No Stir Creamy Almond Butter,spreads,pantry
8,2,43668,9,0,202279,3,5,9,Classic Blend Cole Slaw,packaged vegetables fruits,produce
9,3,33754,1,1,205970,16,5,17,Total 2% with Strawberry Lowfat Greek Strained...,yogurt,dairy eggs

In [160]:
df_sample.shape

(200000, 15)

In [178]:
print(df_sample.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           200000 non-null  int64
 1   product_id         200000 non-null  int64
 2   add_to_cart_order  200000 non-null  int64
 3   reordered          200000 non-null  int64
 4   user_id            200000 non-null  int64
 5   order_number       200000 non-null  int64
 6   order_dow          200000 non-null  int64
 7   order_hour_of_day  200000 non-null  int64
 8   product_name       200000 non-null  object
 9   aisle              200000 non-null  object
 10  department         200000 non-null  object
dtypes: int64(8), object(3)
memory usage: 16.8+ MB
None